// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfnrpkmockjqscwdmupr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmbnJwa21vY2tqcXNjd2RtdXByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4ODM4MjgsImV4cCI6MjA3MzQ1OTgyOH0.d82XQWX-FTZ4pInX9e6OQF7joxgmGHDSIbw13JuDP4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});